services:
  steam-import-service:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    image: steam-import-service:latest
    hostname: steam-import-service.mediamaster.internal
    container_name: steam-import-service.mediamaster.internal
    volumes:
      - ./.env:/app/.env:ro
    networks:
      - mediamaster-internal-network

networks:
  mediamaster-internal-network:
    name: mediamaster-internal-network
